;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mark-word
	mouse-minor-mode-menu
	org-end-of-line
	org-force-self-insert
	))

(setq mc/cmds-to-run-once
      '(
	org-cycle
	org-metaright
	org-self-insert-command
	org-yank
	))
